-- CASO OCORRA ERRO DE GROUP BY
-- set @@sql_mode = 'STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';

-- --------------------------------------------------
-- VIEWS AUXILIARES
-- --------------------------------------------------

-- CALCULA O PREÇO MEDIO DO VALOR PAGO NOS PRODUTOS COMPRADOS
CREATE VIEW VW_PRECO_MEDIO_COMPRAS AS(
	SELECT PC.ID_PRODUTO_COMPRA, 
    PC.ID_PRODUTO,
    SUM(PC.QUANTIDADE*(PC.PRECO_COMPRA-(PC.PRECO_COMPRA*C.DESCONTO)/100))/SUM(PC.QUANTIDADE) AS PRECO_MEDIO_COMPRA, 
    SUM(PC.QUANTIDADE) AS "QTDE_COMPRA"
    FROM PRODUTOS_COMPRAS AS PC
    LEFT JOIN COMPRAS AS C ON  C.ID_COMPRA = PC.ID_COMPRA
	GROUP BY PC.ID_PRODUTO
);

-- CALCULA O PREÇO MEDIO DO VALOR DAS VENDAS COM DESCONTO
CREATE VIEW VW_PRECO_MEDIO_VENDAS AS(
	SELECT PV.ID_PRODUTOS_VENDAS, 
		PV.ID_PRODUTO,
        SUM(PV.QUANTIDADE*(PV.PRECO_VENDA-(PV.PRECO_VENDA*V.DESCONTO)/100))/SUM(PV.QUANTIDADE) AS PRECO_MEDIO_VENDA, 
		SUM(PV.QUANTIDADE) AS QTDE_VENDAS 
    FROM PRODUTOS_VENDAS AS PV
    LEFT JOIN VENDAS AS V ON V.ID_VENDA = PV.ID_VENDA
	GROUP BY PV.ID_PRODUTO
);

-- TOTALIZADOR DE VALORES DAS COMPRAS
CREATE VIEW VW_PRODUTOS_COMPRAS_VALORES_TOTAIS AS (
	SELECT
		PC.ID_PRODUTO_COMPRA,
		PC.ID_COMPRA,
		SUM(QUANTIDADE * PC.PRECO_COMPRA) AS TOTAL_PRODUTOS,
        SUM((QUANTIDADE * PC.PRECO_COMPRA) * ((100 - C.DESCONTO) / 100)) AS TOTAL_DESC
	FROM PRODUTOS_COMPRAS AS PC
	INNER JOIN COMPRAS AS C
		ON C.ID_COMPRA = PC.ID_COMPRA
	GROUP BY
		PC.ID_COMPRA
);	

-- TOTALIZADOR DE VALORES DAS VENDAS
CREATE VIEW VW_PRODUTOS_VENDAS_VALORES_TOTAIS AS (
	SELECT
		PV.ID_PRODUTOS_VENDAS,
		PV.ID_VENDA,
		SUM(PV.QUANTIDADE * PV.PRECO_VENDA) AS TOTAL_PRODUTOS,
        SUM((QUANTIDADE * PV.PRECO_VENDA) * ((100 - V.DESCONTO) / 100)) AS TOTAL_DESC,
        SUM(((QUANTIDADE * PV.PRECO_VENDA) * ((100 - V.DESCONTO) / 100))) AS TOTAL_GASTO
	FROM PRODUTOS_VENDAS AS PV
	INNER JOIN VENDAS AS V
		ON V.ID_VENDA = PV.ID_VENDA
	GROUP BY
		PV.ID_VENDA
);



-- --------------------------------------------------
-- VIEWS PRINCIPAIS
-- --------------------------------------------------

-- RESUMO DE VENDAS (ID DA VENDA, NOME DO CLIENTE, NOME DO VENDEDOR, DATA, VALOR DOS PRODUTOS, DESCONTO, VALOR TOTAL, FORMA DE PAGAMENTO)
CREATE VIEW VW_RESUMO_VENDAS AS (
	SELECT
		VENDAS.ID_VENDA AS "ID VENDA",
		CONCAT(CLI.NOME, " ", CLI.SOBRENOME) AS "CLIENTE",
		CONCAT(VEND.NOME, " ", VEND.SOBRENOME) AS "VENDEDOR",
		DATE_FORMAT(DATA_VENDA, "%d/%m/%Y") AS "DATA DA VENDA",
		CONCAT("R$", FORMAT(TRUNCATE(VAL_TOT.TOTAL_PRODUTOS, 2), 2)) AS "TOTAL PRODUTOS (R$)",
		CONCAT("- R$", FORMAT(TRUNCATE(VAL_TOT.TOTAL_PRODUTOS - VAL_TOT.TOTAL_DESC, 2), 2)) AS "DESCONTO (-)",
		CONCAT("R$", FORMAT(TRUNCATE(VAL_TOT.TOTAL_DESC, 2), 2)) AS "TOTAL VENDA (R$)",
		PAG.NOME AS "FORMA DE PAGAMENTO",
        VENDAS.PARCELAMENTO AS "NÚMERO DE PARCELAS"
	FROM VENDAS
	INNER JOIN CLIENTES AS CLI
		ON CLI.ID_CLIENTE = VENDAS.ID_CLIENTE
	INNER JOIN VENDEDORES AS VEND
		ON VEND.ID_VENDEDOR = VENDAS.ID_VENDEDOR
	INNER JOIN FORMAS_PAGAMENTO AS PAG
		ON PAG.ID_PAGAMENTO = VENDAS.ID_PAGAMENTO
	INNER JOIN VW_PRODUTOS_VENDAS_VALORES_TOTAIS AS VAL_TOT
		ON VAL_TOT.ID_VENDA = VENDAS.ID_VENDA
	ORDER BY
		VENDAS.ID_VENDA ASC
);

-- RESUMO DE COMPRAS (ID DA COMPRA, DATA, VALOR DOS PRODUTOS, DESCONTO, VALOR TOTAL, FORMA DE PAGAMENTO)
CREATE VIEW VW_RESUMO_COMPRAS AS (
	SELECT
		COMPRAS.ID_COMPRA AS "ID COMPRA",
		DATE_FORMAT(DATA_COMPRA, "%d/%m/%Y") AS "DATA DA COMPRA",
		CONCAT("R$", FORMAT(TRUNCATE(COMPRAS_TOT.TOTAL_PRODUTOS,2),2)) AS "TOTAL PRODUTOS (R$)",
		CONCAT("- R$", FORMAT(TRUNCATE(COMPRAS_TOT.TOTAL_PRODUTOS - COMPRAS_TOT.TOTAL_DESC, 2), 2)) AS "DESCONTO (-)",
		CONCAT("R$", FORMAT(TRUNCATE(COMPRAS_TOT.TOTAL_DESC,2),2)) AS "TOTAL DO PEDIDO (R$)",
		PAG.NOME AS "FORMA DE PAGAMENTO"
	FROM COMPRAS
	INNER JOIN FORMAS_PAGAMENTO AS PAG
		ON PAG.ID_PAGAMENTO = COMPRAS.ID_PAGAMENTO
	INNER JOIN VW_PRODUTOS_COMPRAS_VALORES_TOTAIS AS COMPRAS_TOT
		ON COMPRAS_TOT.ID_COMPRA = COMPRAS.ID_COMPRA
	ORDER BY
		COMPRAS.ID_COMPRA ASC
);

-- CLIENTES QUE MAIS GASTARAM $$$ EM NOSSA STORE (NOME, QTDE DE COMPRAS, QTDE DE PRODUTOS COMPRADOS, VALOR TOTAL GASTO
CREATE VIEW VW_CLIENTE_FIEL AS (
	SELECT CONCAT(C.NOME," ", C.SOBRENOME) AS "Nome completo",
		COUNT(V.ID_VENDA) AS "Número de compras",
		SUM(PV.QUANTIDADE) AS "Número de produtos comprados",
		CONCAT("R$", ROUND(VAL_TOT.TOTAL_GASTO,2)) AS "Valor Total Gasto",
		C.EMAIL AS "E-mail",
		C.TELEFONE AS "Telefone"
	FROM CLIENTES AS C
	LEFT JOIN VENDAS AS V ON C.ID_CLIENTE = V.ID_CLIENTE
	LEFT JOIN PRODUTOS_VENDAS AS PV ON V.ID_VENDA = PV.ID_VENDA
    LEFT JOIN VW_PRODUTOS_VENDAS_VALORES_TOTAIS AS VAL_TOT ON VAL_TOT.ID_VENDA = V.ID_VENDA
	GROUP BY C.ID_CLIENTE
	ORDER BY COUNT(V.ID_VENDA) DESC
);

-- RESUMO DOS PRODUTOS (NOME, QUANTIDADE EM ESTOQUE, PREÇO MEDIO DE COMPRA E VENDA, QTDE TOTAL VENDIDA E LUCRO OBTIDO)
CREATE VIEW VW_RESUMO_PRODUTOS AS (
	SELECT P.NOME AS "NOME DO PRODUTO",
		PLAT.NOME AS "PLATAFORMA",
		P.ESTOQUE AS "UNIDADES EM ESTOQUE",
		CONCAT("R$ ",TRUNCATE(PRECO_MEDIO_COMPRA,2)) AS "PREÇO MÉDIO DE COMPRA",
		CONCAT("R$ ",TRUNCATE(PRECO_MEDIO_VENDA,2)) AS "PREÇO MÉDIO DE VENDA",
		QTDE_VENDAS AS "QUANTIDADE TOTAL VENDIDA",
		CONCAT("R$ ",ROUND((PRECO_MEDIO_VENDA-PRECO_MEDIO_COMPRA)*PV.QUANTIDADE,2)) AS "LUCRO TOTAL OBTIDO"
	FROM PRODUTOS AS P
		LEFT JOIN PRODUTOS_COMPRAS AS PC ON P.ID_PRODUTO = PC.ID_PRODUTO
		LEFT JOIN PRODUTOS_VENDAS AS PV ON P.ID_PRODUTO = PV.ID_PRODUTO
		LEFT JOIN VW_PRECO_MEDIO_COMPRAS AS PMC ON P.ID_PRODUTO = PMC.ID_PRODUTO
		LEFT JOIN VW_PRECO_MEDIO_VENDAS AS PMV ON P.ID_PRODUTO = PMV.ID_PRODUTO
        LEFT JOIN PLATAFORMAS AS PLAT ON PLAT.ID_PLATAFORMA = P.ID_PLATAFORMA
		GROUP BY P.ID_PRODUTO
);
