-- TOTALIZADOR DE VALORES DAS VENDAS
CREATE VIEW VW_PRODUTOS_VENDAS_VALORES_TOTAIS AS (
	SELECT
		PV.ID_PRODUTOS_VENDAS,
		PV.ID_VENDA,
		(QUANTIDADE * PV.PRECO_VENDA) AS TOTAL_PRODUTOS,
        ((QUANTIDADE * PV.PRECO_VENDA) * ((100 - V.DESCONTO) / 100)) AS TOTAL_DESC
	FROM PRODUTOS_VENDAS AS PV
	INNER JOIN VENDAS AS V
		ON V.ID_VENDA = PV.ID_VENDA
	GROUP BY
		PV.ID_VENDA
);

SELECT * FROM VW_PRODUTOS_VENDAS_VALORES_TOTAIS;

-- RESUMO DE VENDAS (ID DA VENDA, NOME DO CLIENTE, NOME DO VENDEDOR, DATA, VALOR DOS PRODUTOS, DESCONTO, VALOR TOTAL, FORMA DE PAGAMENTO)
CREATE VIEW VW_RESUMO_VENDAS AS (
	SELECT
		VENDAS.ID_VENDA AS "ID VENDA",
		CONCAT(CLI.NOME, " ", CLI.SOBRENOME) AS "CLIENTE",
		CONCAT(VEND.NOME, " ", VEND.SOBRENOME) AS "VENDEDOR",
		DATE_FORMAT(DATA_VENDA, "%d/%m/%Y") AS "DATA DA VENDA",
		CONCAT("R$", FORMAT(TRUNCATE(VAL_TOT.TOTAL_PRODUTOS, 2), 2)) AS "TOTAL PRODUTOS (R$)",
		CONCAT("- R$", FORMAT(TRUNCATE(VAL_TOT.TOTAL_PRODUTOS - VAL_TOT.TOTAL_DESC, 2), 2)) AS "DESCONTO (-)",
		CONCAT("R$", FORMAT(TRUNCATE(VAL_TOT.TOTAL_DESC, 2), 2)) AS "TOTAL VENDA (R$)",
		PAG.NOME AS "FORMA DE PAGAMENTO"
	FROM VENDAS
	INNER JOIN CLIENTES AS CLI
		ON CLI.ID_CLIENTE = VENDAS.ID_CLIENTE
	INNER JOIN VENDEDORES AS VEND
		ON VEND.ID_VENDEDOR = VENDAS.ID_VENDEDOR
	INNER JOIN FORMAS_PAGAMENTO AS PAG
		ON PAG.ID_PAGAMENTO = VENDAS.ID_PAGAMENTO
	INNER JOIN VW_PRODUTOS_VENDAS_VALORES_TOTAIS AS VAL_TOT
		ON VAL_TOT.ID_VENDA = VENDAS.ID_VENDA
	ORDER BY
		VENDAS.ID_VENDA ASC
);

SELECT * FROM VW_RESUMO_VENDAS;



-- TOTALIZADOR DE VALORES DAS COMPRAS
CREATE VIEW VW_PRODUTOS_COMPRAS_VALORES_TOTAIS AS (
	SELECT
		PC.ID_PRODUTO_COMPRA,
		PC.ID_COMPRA,
		(QUANTIDADE * PC.PRECO_COMPRA) AS TOTAL_PRODUTOS,
        ((QUANTIDADE * PC.PRECO_COMPRA) * ((100 - C.DESCONTO) / 100)) AS TOTAL_DESC
	FROM PRODUTOS_COMPRAS AS PC
	INNER JOIN COMPRAS AS C
		ON C.ID_COMPRA = PC.ID_COMPRA
	GROUP BY
		PC.ID_COMPRA
);

SELECT * FROM VW_PRODUTOS_COMPRAS_VALORES_TOTAIS;


-- RESUMO DE COMPRAS (ID DA COMPRA, DATA, VALOR DOS PRODUTOS, DESCONTO, VALOR TOTAL, FORMA DE PAGAMENTO)
CREATE VIEW VW_RESUMO_COMPRAS AS (
	SELECT
		COMPRAS.ID_COMPRA AS "ID COMPRA",
		DATE_FORMAT(DATA_COMPRA, "%d/%m/%Y") AS "DATA DA COMPRA",
		CONCAT("R$", FORMAT(TRUNCATE(COMPRAS_TOT.TOTAL_PRODUTOS, 2), 2)) AS "TOTAL PRODUTOS (R$)",
		CONCAT("- R$", FORMAT(TRUNCATE(COMPRAS_TOT.TOTAL_PRODUTOS - COMPRAS_TOT.TOTAL_DESC, 2), 2)) AS "DESCONTO (-)",
		CONCAT("R$", FORMAT(TRUNCATE(COMPRAS_TOT.TOTAL_DESC, 2), 2)) AS "TOTAL DO PEDIDO (R$)",
		PAG.NOME AS "FORMA DE PAGAMENTO"
	FROM COMPRAS
	INNER JOIN FORMAS_PAGAMENTO AS PAG
		ON PAG.ID_PAGAMENTO = COMPRAS.ID_PAGAMENTO
	INNER JOIN VW_PRODUTOS_COMPRAS_VALORES_TOTAIS AS COMPRAS_TOT
		ON COMPRAS_TOT.ID_COMPRA = COMPRAS.ID_COMPRA
	ORDER BY
		COMPRAS.ID_COMPRA ASC
);

SELECT * FROM VW_RESUMO_COMPRAS;

