-- FUNÇÕES DE AGREGAÇÃO
-- OBJETIVOS: MONTAR CONSULTAS (SELECTS) QUE VISAM RETORNAR OS DADOS DE MANEIRA AGRUPADA/RESUMIDA A PARTIR DE UM CONJUNTO DE DADOS

	

-- FUNÇÃO COUNT
-- OBJETIVO: CONTAR A QUANTIDADE DE REGISTROS QUE FORAM ENCONTRADOS A PARTIR DO SELECT INFORMADO
-- COUNT PARA TRAZER A QUANTIDADE DE REGISTROS DA TABELA DE FATURAS
	SELECT
		COUNT(*) AS 'QUANTIDADE DE FATURAS'
	FROM FATURAS;

	SELECT
		COUNT(*) AS 'QUANTIDADE DE FATURAS DO RIO DE JANEIRO'
	FROM FATURAS
	WHERE
		CidadeEnvio = 'Rio de Janeiro';
    

-- MAX
-- OBJETIVO: RETORNAR O VALOR MÁXIMO A PARTIR DE UM CONJUNTO DE DADOS
	SELECT 
		MAX(TRANSPORTE) AS 'VALOR MÁXIMO'
	FROM FATURAS;

-- MIN
-- OBJETIVO: RETORNAR O VALOR MÍNIMO A PARTIR DE UM CONJUNTO DE DADOS
	SELECT
		MIN(TRANSPORTE) AS 'VALOR MINIMO'
	FROM FATURAS;

-- AVG
-- OBJETIVO: RETORNA A MÉDIA A PARTIR DE UM CONJUNTO DE DADOS

	-- SEM ARREDONDAMENTO
	SELECT
		AVG(TRANSPORTE)
	FROM FATURAS;

	-- COM ARREDONDAMENTO
	SELECT
		ROUND(AVG(TRANSPORTE), 2)
	FROM FATURAS;
    
-- SUM
-- OBJETIVO: RETORNA A SOMA DE UM CONJUNTO DE DADOS
	SELECT
		CONCAT('R$', SUM(TRANSPORTE))
	FROM
		FATURAS;

    
-- GROUP BY (CLÁUSULA DE AGREGAÇÃO)
-- OBJETIVO: RETORNA UM CONJUNTO DE DADOS QUE SE REPETE
	SELECT
		CIDADEENVIO,
		COUNT(*)
	FROM
		FATURAS
	GROUP BY
		CIDADEENVIO;
    
-- HAVING
-- OBJETIVO: APLICAR UMA CONDIÇÃO AO GROUP BY
	SELECT 
		CIDADEENVIO,
        COUNT(*)
	FROM FATURAS
    GROUP BY
		CIDADEENVIO
	HAVING
		COUNT(*) > 30;
        
-- FUNÇÕES DE FORMATAÇÃO
-- OBJETIVO : FORMATAR OS DADOS RETORNADOS A PARTID DE UM SELECT
-- CAST()
-- CONCAT()
-- DATE_FORMAT()

-- DATE_FORMAT()
	SELECT
		DATE_FORMAT(DATAREGISTRO,  '%d/%m/%y')
	FROM FATURAS;


-- SUBQUERIES
-- OBJETIVO: REALIZAR BUSCA DE DADOS EM VALORES DENTRO DE OUTRAS BUSCAS

-- SEM SUBQUERY
	SELECT
		*
	FROM FATURAS
	WHERE
		CLIENTEID = 'ALFKI';
    
-- COM SUBQUERY
	SELECT
		*
	FROM FATURAS
	WHERE
		CLIENTEID = (
			SELECT
				CLIENTEID
			FROM CLIENTES
			WHERE
				EMPRESA = 'Alfreds Futterkiste'
		);

        

