-- DDL

-- CREATE TABLE
-- INSTRUÇÃO RESPONSÁVEL POR CRIAR UMA TABELA DENTRO DO NOSSO BANCO DE DADOS.alter
CREATE TABLE ALUNO (
	-- NOME_ATRIBUTO
    -- TIPO DO DADO
    -- RESTRIÇÃO (SIM OU NÃO)
    ID_ALUNO INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    NOME_ALUNO VARCHAR(150),
    ENDERECO VARCHAR(150)
);

-- DROP TABLE
-- INSTRUÇÃO RESPONSÁVEL POR REMOVER UMA TABELA DO MEU BANCO DE DADOS
DROP TABLE ALUNO;

-- ALTER TABLE
-- INSTRUÇÃO RESPONSÁVEL POR ALTERAR A ESTRUTURA DE UMA TABELA
ALTER TABLE ALUNO
ADD COLUMN CPF VARCHAR(20);

ALTER TABLE ALUNO
ADD COLUMN NR_TELEFONE VARCHAR(20);

ALTER TABLE ALUNO
DROP COLUMN CPF;