-- DML
-- CONJUNTO DE INSTRUÇÕES RESPONSÁVEIS POR GERENCIAR E MANIPULAR OS REGISTROS DAS TABELAS

-- INSERT
-- INSTRUÇÃO RESPONSÁVEL POR INSERIR UM DADO (REGISTRO) EM UMA TABELA
INSERT INTO ALUNO(NOME_ALUNO, ENDERECO, NR_TELEFONE)
VALUES
('Guilherme', 'Rua 123',  '(11) 123456789'),
('Cauê', 'Rua 123',  '(11) 123456789'),
('Larissa', 'Rua 123',  '(11) 123456789'),
('Jorge', 'Rua 123',  '(11) 123456789'),
('Paulo', 'Rua 123',  '(11) 123456789');

-- SELECT
-- INSTRUÇÃO RESPONSÁVEL POR CONSULTAR OS REGISTROS DE UMA TABELA
SELECT * FROM ALUNO;
SELECT NOME_ALUNO FROM ALUNO;

-- DELETE
-- INSTRUÇÃO RESPONSÁVEL POR REMOÇÃO DO REGISTRO DA TABELA
DELETE FROM ALUNO
WHERE NOME_ALUNO = 'Jorge';

-- UPDATE
-- INSTRUÇÃO RESPONSÁVEL POR ATUALIZAR INFORMAÇÕES DE UM REGISTRO
UPDATE ALUNO
SET
	ID_ALUNO = 22
WHERE
	ID_ALUNO = 17;