-- MESA DE TRABALHO | AULA 17 | BANCO DE DADOS I | 07/06/2022

-- EQUIPE 1
-- CAUÊ SILVEIRA
-- FELIPE OTONI
-- MICHEL VIEIRA
-- LAURA FREITAS
-- MATHEUS RIBEIRO
-- RAFAEL VARELA

-- VIEW - Parte I

-- Clientes
-- 1.
CREATE VIEW VW_DADOS_CLIENTES AS (
SELECT
	CLIENTEID AS 'ID',
    CONTATO,
    FAX,
    TELEFONE
FROM CLIENTES
);


-- 2.B
SELECT
	TELEFONE
FROM CLIENTES
WHERE
	FAX = 0;
   
   
-- 2.B
SELECT
	TELEFONE
FROM VW_DADOS_CLIENTES
WHERE
	FAX = 0;
    
-- Fornecedores
-- 1.

CREATE VIEW VW_DADOS_FORNECEDORES AS (
SELECT
	PROVEDORID AS 'ID',
    EMPRESA,
    CONTATO,
    CONCAT(ENDERECO, ', ', CIDADE, ', ', CODIGOPOSTAL, ', ', PAIS) AS 'ENDEREÇO'
FROM PROVEDORES
);

-- 2.A
SELECT
	EMPRESA
FROM PROVEDORES
WHERE
	ENDERECO LIKE '%Av%Americanas%';
    
-- 2.B
SELECT
	EMPRESA
FROM VW_DADOS_FORNECEDORES
WHERE
	`ENDEREÇO` LIKE '%Av%Americanas%';
    
    
-- VIEW - Parte II - Desafio
-- 1.

CREATE VIEW VW_DADOS_PRODUTOS AS (
SELECT
	PRODUTOID AS 'ID',
    PRODUTONOME,
    ROUND(PRECOUNITARIO, 0) AS 'PREÇO UNITÁRIO',
    UNIDADESESTOQUE AS 'UNIDADES EM ESTOQUE',
    UNIDADESPEDIDAS AS 'UNIDADES ENCOMENDADAS',
    CASE
		WHEN UNIDADESPEDIDAS = 0 THEN 'BAIXA'
        WHEN UNIDADESPEDIDAS < UNIDADESESTOQUE THEN 'MÉDIA'
        WHEN UNIDADESPEDIDAS <= (UNIDADESESTOQUE * 2) THEN 'URGENTE'
        ELSE 'PRIORITÁRIO'
	END AS 'PRIORIDADE'
FROM PRODUTOS
);

-- 2.
SELECT
	PRIORIDADE,
    COUNT(`ID`) AS 'QUANTIDADE',
    CONCAT('R$', ROUND(AVG(`PREÇO UNITÁRIO`), 2)) AS 'PREÇO MÉDIO'
FROM VW_DADOS_PRODUTOS
GROUP BY
	PRIORIDADE
HAVING
	COUNT(`ID`) > 5;