-- EQUIPE 1
-- MESA DE TRABALHO - BANCO DE DADOS I - 23/05/2022

-- INTEGRANTES:
-- CAUÊ SILVEIRA
-- PAULO BORGES
-- AMANDA REIS
-- MICHEL NASCIMENTO
-- JOSIANE MOTA
-- DIOGO RODRIGUES

-- DDL

-- CRIAÇÃO E SELEÇÃO DO BANCO DE DADOS
CREATE DATABASE DHTube;
USE DHTube;

-- CRIANDO TABELAS E RELACIONAMENTOS
CREATE TABLE AVATAR (
	ID_AVATAR INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(45),
    URL_IMAGEM VARCHAR(45)
);

CREATE TABLE PAIS (
	ID_PAIS INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(100)
);

CREATE TABLE USUARIO (
	ID_USUARIO INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(45),
    EMAIL VARCHAR(45),
    SENHA VARCHAR(45),
    DATA_NASCIMENTO DATETIME,
    CEP VARCHAR(45),
    ID_PAIS INT NOT NULL,
    ID_AVATAR INT NOT  NULL,
    CONSTRAINT FK_USUARIO_PAIS FOREIGN KEY (ID_PAIS) REFERENCES PAIS(ID_PAIS),
    CONSTRAINT FK_USUARIO_AVATAR FOREIGN KEY (ID_AVATAR) REFERENCES AVATAR(ID_AVATAR)
);