-- MESA DE TRABALHO - AULA 16 - BANCO DE DADOS I

-- EQUIPE 5
-- CAIRO OLIVEIRA
-- CAUÊ SILVEIRA
-- DANIELA FUENMAYOR
-- MICHEL VIEIRA

-- Relatórios II parte I - Revisando INNER JOIN

SELECT
	F.FATURAID AS 'Id da Fatura',
    DATE_FORMAT(F.DATAFATURA, '%d/%m/%y') AS 'Data da Fatura',
	CO.EMPRESA AS 'Forma de Envio',
    CLI.EMPRESA AS 'Nome do Cliente',
	CAT.CATEGORIANOME AS 'Categoria do Produto',
    PROD.PRODUTONOME AS 'Produto',
    CONCAT("R$", PROD.PRECOUNITARIO) AS 'Preço Unitário',
    DET.QUANTIDADE AS 'Quantidade'
FROM FATURAS AS F
INNER JOIN CORREIOS AS CO ON CO.CORREIOID = F.FORMAENVIO
INNER JOIN CLIENTES AS CLI ON CLI.CLIENTEID = F.CLIENTEID
INNER JOIN DETALHEFATURA AS DET ON DET.FATURAID = F.FATURAID
INNER JOIN PRODUTOS AS PROD ON PROD.PRODUTOID = DET.PRODUTOID
INNER JOIN CATEGORIAS AS CAT ON CAT.CATEGORIAID = PROD.CATEGORIAID;

-- Relatórios II parte II - INNER, LEFT e RIGHT JOIN

-- 1.
SELECT
	CAT.CATEGORIANOME AS 'Categoria',
    PROD.PRODUTONOME AS 'Produto'
FROM CATEGORIAS AS CAT
LEFT JOIN PRODUTOS AS PROD ON CAT.CATEGORIAID = PROD.CATEGORIAID;

-- 2.
SELECT
	CLI.EMPRESA AS 'Cliente',
    F.FATURAID
FROM CLIENTES AS CLI
LEFT JOIN FATURAS AS F ON CLI.CLIENTEID = F.CLIENTEID
WHERE
	FATURAID IS NULL;
    
-- 3.
SELECT
	PROD.PRODUTONOME AS 'Produto',
    CAT.CATEGORIANOME AS 'Categoria',
    FORN.EMPRESA AS 'Fornecedor',
    FORN.CONTATO AS 'CONTATO'
FROM PRODUTOS AS PROD
LEFT JOIN CATEGORIAS AS CAT ON PROD.CATEGORIAID = CAT.CATEGORIAID
LEFT JOIN PROVEDORES AS FORN ON PROD.PROVEDORID = FORN.PROVEDORID;

-- 4.
SELECT
	CAT.CATEGORIANOME AS 'Categoria',
    AVG(PROD.PRECOUNITARIO) AS 'Preço Unitário Médio'
FROM CATEGORIAS AS CAT
LEFT JOIN PRODUTOS AS PROD ON CAT.CATEGORIAID = PROD.CATEGORIAID
GROUP BY
	CAT.CATEGORIANOME;

-- 5.
SELECT
	CLI.EMPRESA AS 'Cliente',
    MAX(F.FATURAID) AS 'Última Fatura'
FROM CLIENTES AS CLI
RIGHT JOIN FATURAS AS F ON F.CLIENTEID = CLI.CLIENTEID
GROUP BY
	CLI.EMPRESA;

-- 6.
SELECT
	COR.EMPRESA AS 'Forma de Envio',
    COUNT(F.FATURAID) AS 'Quantidade de Faturas'
FROM CORREIOS AS COR
RIGHT JOIN FATURAS AS F ON F.FORMAENVIO = COR.CORREIOID
GROUP BY
	COR.EMPRESA;
