/* ORDEM DE CRIAÇÃO DE TABELAS: SETOR > REQUISITANTE > OFICINA > ESPECIALIDADE/EQUIPAMENTO > TECNICO > TREINAMENTO > OS*/

/* DIRETRIZES E ATERAÇÕES EM REALAÇÃO AO MODELO DE REFERÊNCIA (CHECKPOINT I)

- 1. VARCHAR PADRONIZADO PARA TAMANHOS 50 E 100
- 2. ESPECIALIDADE.INSALUBRIDADE E ESPECIALIDADE.PERICULOSIDADE DEIXARAM DE SER 'NOT NULL' E PASSARAM A TER UM VALOR PADRÃO (DEFAULT) IGUAL A 0 (FALSE);
- 3. EQUIPAMENTO (FABRICANTE, MODELO E NUMERO_SERIE) DEIXARAM DE SER 'NOT NULL';
- 4. TECNICO.ASO_OK PASSOU A SER 'NOT NULL', POIS DETERMINA QUANDO UM TECNICO PODE SER ESCALADO PARA REALIZAÇÃO DE UMA OS;
- 5. TECNICO.SOBRENOME DEIXOU DE SER 'NOT NULL';
- 6. TREINAMENTO.NR DEIXOU DE SER 'NOT NULL' E PASSOU A TER UM VALOR PADRÃO (DEFAULT) IGUAL A 0 (FALSE);
- 7. OS.DESCRICAO E OS.COMENTARIOS ALTERADOS DE TEXT PARA VARCHAR(250) POR MOTIVOS DE DESEMPENHO E TAMANHO SUFICIENTE;
- 8. OS.GRAU_PRIORIDADE E OS.SITUACAO DEIXOU DE SER 'NOT NULL' E PASSARAM A TER UM VALOR PADRÃO (DEFAULT) IGUAL A 'BAIXA' E 'ABERTA', RESPECTIVAMENTE;*/


/* EXCLUINDO BASE DE DADOS SE JÁ EXISTENTE */
DROP DATABASE IF EXISTS SISMANUT;

/* CRIANDO BASE DE DADOS */
CREATE DATABASE IF NOT EXISTS SISMANUT;

/* USANDO A BASE DE DADOS */
USE SISMANUT;

/* CRIANDO TABELA SETOR */
CREATE TABLE IF NOT EXISTS SETOR (
    ID_SETOR INT NOT NULL AUTO_INCREMENT,
    NOME_SETOR VARCHAR(100),
    PRIORITARIO BOOLEAN,
    PRIMARY KEY (ID_SETOR)
);

/* CRIANDO TABELA REQUISITANTE */
CREATE TABLE IF NOT EXISTS REQUISITANTE (
    ID_REQUISITANTE INT NOT NULL AUTO_INCREMENT,
    ID_SETOR INT NOT NULL,
    NOME VARCHAR(50) NOT NULL,
    SOBRENOME VARCHAR(100),
    PODE_SOLICITAR BOOLEAN NOT NULL DEFAULT 1,
    PRIMARY KEY (ID_REQUISITANTE),
    CONSTRAINT FK_REQUISITANTE_SETOR
        FOREIGN KEY (ID_SETOR)
        REFERENCES SETOR (ID_SETOR)
);

/* CRIANDO TABELA OFICINA */
CREATE TABLE IF NOT EXISTS OFICINA (
    ID_OFICINA INT NOT NULL AUTO_INCREMENT,
    NOME_OFICINA VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID_OFICINA)
);

/* CRIANDO TABELA ESPECIALIDADE */
CREATE TABLE IF NOT EXISTS ESPECIALIDADE (
    ID_ESPECIALIDADE INT NOT NULL AUTO_INCREMENT,
    ID_OFICINA INT NOT NULL,
    NOME_ESPECIALIDADE VARCHAR(50) NOT NULL,
    INSALUBRIDADE BOOLEAN DEFAULT 0,
    PERICULOSIDADE BOOLEAN DEFAULT 0,
    PRIMARY KEY (ID_ESPECIALIDADE),
    CONSTRAINT FK_ESPECIALIDADE_OFICINA
        FOREIGN KEY (ID_OFICINA)
        REFERENCES OFICINA (ID_OFICINA)
);

/* CRIANDO TABELA EQUIPAMENTO */
CREATE TABLE IF NOT EXISTS EQUIPAMENTO (
    ID_EQUIPAMENTO INT NOT NULL AUTO_INCREMENT,
    ID_OFICINA INT NOT NULL,
    FABRICANTE VARCHAR(50),
    MODELO VARCHAR(50),
    NUMERO_SERIE VARCHAR(50),
    PRIMARY KEY (ID_EQUIPAMENTO),
    CONSTRAINT FK_EQUIPAMENTO_OFICINA
        FOREIGN KEY (ID_OFICINA)
        REFERENCES OFICINA (ID_OFICINA)
);

/* CRIANDO TABELA TECNICO */
CREATE TABLE IF NOT EXISTS TECNICO (
    ID_TECNICO INT NOT NULL AUTO_INCREMENT,
    ID_ESPECIALIDADE INT NOT NULL,
    NOME VARCHAR(50) NOT NULL,
    SOBRENOME VARCHAR(100),
    ASO_OK BOOLEAN NOT NULL,
    PRIMARY KEY (ID_TECNICO),
    CONSTRAINT FK_TECNICO_ESPECIALIDADE
        FOREIGN KEY (ID_ESPECIALIDADE)
        REFERENCES ESPECIALIDADE (ID_ESPECIALIDADE)
);

/* CRIANDO TABELA TREINAMENTO */
CREATE TABLE IF NOT EXISTS TREINAMENTO (
    ID_TREINAMENTO INT NOT NULL AUTO_INCREMENT,
    ID_TECNICO INT NOT NULL,
    TITULO_TREINAMENTO VARCHAR(100) NOT NULL,
    NR BOOLEAN DEFAULT 0,
    VALIDADE DATE NOT NULL,
    PRIMARY KEY (ID_TREINAMENTO),
    CONSTRAINT FK_TREINAMENTO_TECNICO
        FOREIGN KEY (ID_TECNICO)
        REFERENCES TECNICO (ID_TECNICO)
);

/* CRIANDO TABELA OS */
CREATE TABLE IF NOT EXISTS OS (
    ID_OS INT NOT NULL AUTO_INCREMENT,
    ID_REQUISITANTE INT NOT NULL,
    ID_OFICINA INT NOT NULL,
    ID_TECNICO INT,
    ID_EQUIPAMENTO INT,
    TIPO_OS VARCHAR(50) NOT NULL,
    DESCRICAO VARCHAR(250) NOT NULL,
    GRAU_PRIORIDADE VARCHAR(50) DEFAULT 'BAIXA',
    DATA_SOLICITACAO DATE NOT NULL,
    DATA_CONCLUSAO DATE,
    SITUACAO VARCHAR(50) DEFAULT 'ABERTA',
    COMENTARIOS VARCHAR(250),
    PRIMARY KEY (ID_OS),
    CONSTRAINT FK_OS_REQUISITANTE
        FOREIGN KEY (ID_REQUISITANTE)
        REFERENCES REQUISITANTE (ID_REQUISITANTE),
    CONSTRAINT FK_OS_OFICINA
        FOREIGN KEY (ID_OFICINA)
        REFERENCES OFICINA (ID_OFICINA),
    CONSTRAINT FK_OS_TECNICO
        FOREIGN KEY (ID_TECNICO)
        REFERENCES TECNICO (ID_TECNICO),
    CONSTRAINT FK_OS_EQUIPAMENTO
        FOREIGN KEY (ID_EQUIPAMENTO)
        REFERENCES EQUIPAMENTO (ID_EQUIPAMENTO)
);



/* ALTERANDO A TABELA (ENTIDADE) 'EQUIPAMENTO' - INCLUSÃO DE COLUNA (ATRIBUTO) (EXEMPLO DE UTILIZAÇÃO DE ALTER)*/
ALTER TABLE EQUIPAMENTO
ADD TIPO_EQUIPAMENTO VARCHAR(50);