DELIMITER $$
CREATE PROCEDURE SP_NUMERO_PRIMO(
	IN NUMERO INT,
    OUT RETORNOPRIMOSIMNAO VARCHAR(255)
)
BEGIN 
	DECLARE I INT;
    DECLARE C INT;
    SET C = 0;
    SET I = NUMERO;
    
    laco: LOOP
    IF (I <> 1) THEN
		IF ((NUMERO % I) = 0) THEN
			SET	C = C + 1;
            SET I = I - 1;
	ELSE
		LEAVE laco;
	END IF;
	END LOOP laco;
    
    IF (C > 2) THEN
		SET RETORNOPRIMOSIMNAO = 'Não é primo';
    ELSE
		SET RETORNOPRIMOSIMNAO = 'É primo';
	END IF;
END $$

CALL SP_NUMERO_PRIMO(15, @RETORNOPRIMOSIMNAO);
SELECT @RETORNOPRIMOSIMNAO;

DROP PROCEDURE SP_NUMERO_PRIMO